name: dotmap
description: Allows you to create, set and get Map rows using dot notated strings.

version: 1.0.0
homepage: https://github.com/p4-k4

environment:
  sdk: '>=2.15.1 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
